# Generated by Django 6.0.2 on 2026-02-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('target_audience', models.TextField()),
                ('brand_voice', models.CharField(max_length=255)),
                ('goals', models.TextField()),
                ('offer_details', models.TextField(blank=True)),
                ('platforms', models.CharField(help_text='Comma-separated platforms, e.g. Instagram, LinkedIn, X', max_length=255)),
                ('extra_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('platform_variants', models.JSONField(blank=True, default=dict)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('cta', models.CharField(max_length=500)),
                ('image_prompt', models.TextField()),
                ('creative_suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_posts', to='ai_generator.project')),
            ],
        ),
    ]
