# Generated by Django 4.2.7 on 2026-02-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedpost',
            name='creative_suggestions',
        ),
        migrations.RemoveField(
            model_name='generatedpost',
            name='platform_variants',
        ),
        migrations.RemoveField(
            model_name='project',
            name='brand_voice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='extra_context',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='project',
            name='offer_details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='platforms',
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='color_theme_suggestion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='creative_type',
            field=models.CharField(default='Static Post', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='facebook_version',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='instagram_version',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='linkedin_version',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='post_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='post_topic',
            field=models.CharField(default='General Post', max_length=255),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='publish_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='text_overlay_suggestion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.CharField(default='Engagement', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_posts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=3),
        ),
        migrations.AddField(
            model_name='project',
            name='tone',
            field=models.CharField(default='Professional', max_length=50),
        ),
    ]
